
name: variables and secrets

env: 
  WF_VAR: "Workflow Level Variable"

on:
  push:

jobs:
  test_variables:
    env:
      JOB_VAR: "Job Level Variable"
    name: Job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP_VAR: "Step Level Variable"
        run: |
          echo ${{ github_actor }}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRETS }}
